local utils = require('utils')

utils.map("n", "fw", ":HopWord <CR>")
utils.map("n", "fh", ":HopWord <CR>")
utils.map("n", "fp", ":HopPattern <CR>")
utils.map("n", "f1", ":HopChar1 <CR>")
utils.map("n", "ff", ":HopChar1 <CR>")
utils.map("n", "fg", ":HopChar2 <CR>")
utils.map("n", "f2", ":HopChar2 <CR>")
utils.map("n", "fl", ":HopLine <CR>")
