local utils = require('utils')

utils.map("n", "fw", ":HopWord <CR>", { silent = true })
utils.map("n", "fh", ":HopWord <CR>", { silent = true })
utils.map("n", "fp", ":HopPattern <CR>", { silent = true })
utils.map("n", "f1", ":HopChar1 <CR>", { silent = true })
utils.map("n", "ff", ":HopChar1 <CR>", { silent = true })
utils.map("n", "fg", ":HopChar2 <CR>", { silent = true })
utils.map("n", "f2", ":HopChar2 <CR>", { silent = true })
utils.map("n", "fl", ":HopLine <CR>", { silent = true })
